### ISSUE TITLE
How do I use in react-navigation v5

### ISSUE THREAD

**Issue by yigithanyucedag** [wonday/react-native-orientation-locker#120]
Is this library support react-navigation v5?

**Comment by zmefz** [comment]
@yigithanyucedag Yes it works but when the orientation is changing the user will see many weird navigation artifacts like jumping footer/header and so on. So it make sense to find a solution on how to at least hide the application content while the orientation change is in progress and some time after it because it takes some time for react-navigation to display content in a right way after orientation change.

**Comment by yigithanyucedag** [comment]
Someone should fix these bugs.

**Comment by BooDzioo** [comment]
Did someone found a solution for that issue?

**Comment by orzhtml** [comment]
Did someone found a solution for that issue?

**Comment by opensw** [comment]
I know it is an old post, but if someone like me needs a solution to this issue with react-nativation library, you can set the initial orientation via `screenOptions:{screenOrientation: "portrait"}` field of `Stack.Navigator ` or via `options: {screenOrientation: "portrait"}` field on each of your `Stack.Screen`

Just a quick snippet

```
enum EnumNavigation {
    page1: 'page1',
    page2: 'page2',
}

const Screens = [
    { name: EnumNavigation.page1, component: AppPage1, options: {screenOrientation: "portrait"}},
    { name: EnumNavigation.page2, component: AppPage2, options: {screenOrientation: "portrait"}},
];

const App = () => {
    return (
        ...
        <NavigationContainer>
          <Stack.Navigator
            initialRouteName={EnumNavigation.page1}
            screenOptions={{
              headerShown: false,
            }}
          >
            {
              Screens.map((screen, index) => {
                return (
                  <Stack.Screen key={'Screen ' + index} { ...screen } />
                )
              })
            }
          </Stack.Navigator>
        </NavigationContainer>
        ...
    );
```
