### ISSUE TITLE
orientationDidChange, Why extend it by one second?

### ISSUE THREAD

**Issue by cuibeihong** [wonday/react-native-orientation-locker#35]
![image](https://user-images.githubusercontent.com/18608903/49621398-1c819b00-fa00-11e8-9f44-2e8892bb5283.png)

**Comment by gp3gp3gp3** [comment]
Good question.  This is causing some performance issues in my app.

**Comment by gp3gp3gp3** [comment]
Also, adding timeouts in react native apps [have to be cleared out when dismissed](https://facebook.github.io/react-native/docs/timers#timermixin), or else this will lead to [memory leaks](https://blog.swmansion.com/hunting-js-memory-leaks-in-react-native-apps-bd73807d0fde)

**Comment by wonday** [comment]
I add this because, I had caused a problem.
When switching orientation, if you get screen width/height immediately, maybe you got the wrong value 
(the last orientation screen width/height, not the target orientation screen width/height).
wait 1000 ms make sure switching finish.
It seems not a good solution...

**Comment by wonday** [comment]
remove it from v1.1.0
